version: '3.8'

services:

  producer:
    build:
      dockerfile: Dockerfile
      context: .
    command: pipenv run producer

  consumer:
    build:
      dockerfile: Dockerfile
      context: .
    command: pipenv run consumer
