version: '3.8'

services:

  producer:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: 5000
    command: pipenv run producer

  consumer:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PRODUCER_PORT: 5000
      PRODUCER_HOST: producer

    command: pipenv run consumer
